sudo: required
dist: trusty

matrix:
  include:
    - compiler: gcc
      env: COMPILER=g++-4.9

before_install:
  - bin/dependencies.sh
    
script:
  - cpplint --recursive src include
  - make all
  - coveralls-lcov build/coverage/coverage.info
