language: c

env:
  - PGVERSION=9.1

before_script:
  - PATH=/usr/lib/postgresql/$PGVERSION/bin:$PATH
  
  
script:
  - env
  - which psql
  - /usr/lib/postgresql/9.3/bin/psql -c "select version()"
  - make test
