language: c

env:
#  - PGVERSION=9.1
  - PGVERSION=9.2
#  - PGVERSION=9.3

before_script:
  - export PATH=/usr/lib/postgresql/$PGVERSION/bin:$PATH
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start $PGVERSION
  - sudo apt-get install postgresql-plpython-$PGVERSION
  
script:
  - which psql
  - psql --version
  - make test
