language: c

env:
#  - PGVERSION=9.1
#  - PGVERSION=9.2
  - PGVERSION=9.3

before_script:
  # Start the correct version of postgres
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start $PGVERSION  
  
script:
  - pg_config
  - python --version
  - psql -c "create language plpythonu; create function pwd() returns text as 'import os;return os.getcwd()' language plpythonu; SELECT pwd(), version()"  template1
  
  - make test
